spring:
  batch:
    job:
      enabled: false
  datasource:
    url: jdbc:mysql://localhost:3306/mysql
    username: root
    password: 1qaz!QAZ
    driver-class-name: com.mysql.cj.jdbc.Driver









